version: '2.0'

services:
        fuzzagent:
                build: 
                        context: fuzzagent
                        args:
                               - DNH_REPO=https://github.com/Chris-plus-alphanumericgibberish/dNAO.git
                               - DNH_FOLDER=dNAO
                restart: always
                environment:
                        DNH_DIR: "dnethackdir"
                        DNH_GAME: "dnethack"

                cap_add:
                        - SYS_PTRACE 
                security_opt:
                        - seccomp:unconfined
                tty: true

